4단계 - 계산기 UI
next-step/android-calculator-mvc pull request #154
Opened 2022-07-16 14:05 UTC by greedy0110

### 주요 설계

- CalculatorDisplayModel
  - UI에 입력되는 값에 따라서 적절한 처리 및 저장해서 display할 text를 노출하는 책임
- MainActivityDisplayTest
  - 실제 view와 연동되는 통합 테스트

2022-07-16 14:09 UTC, greedy0110 commented on app/src/main/java/edu/nextstep/camp/calculator/CalculatorDisplayModel.kt
> +            }
뭔가 단순하게 묶어낼 수 있을 것 같으면서도 state 패턴 등으로 풀어내기 어려워서 그대로 뒸습니다 🤔

고민했던 것

마지막 입력 값에 따라서 동작이 달라지니 그에 따라 EmptyState, OperandState, OperatorState 이런 식으로 구분하고 여기에서는 currentState에 대해서 put 하는 식으로 할까 했는데요. currentState를 갱신하는 쪽 코드가 난해하다고 생각이들어서... (delete 시점에는 이전 state에 대한 정보도 필요하는 등) 복잡해지더라고요. 어떤 식으로 풀어낼 수 있을지..

2022-07-16 14:10 UTC, greedy0110 commented on domain/src/main/java/edu/nextstep/camp/calculator/domain/Tokenizer.kt
> +    private val symbol: String,
여건 step3 마지막 코멘트 반영입니다.

2022-07-17 02:24 UTC, laco-dev requested changes
4단계 잘 해주셨습니다. 🙏🏻 

컨트롤러 역할을 조금이라도 분리해보려는 노력이 보기 좋았습니다.
MVVM 구현처럼 만들어 진 느낌도 드네요!

몇 가지 피드백을 남겨보았습니다.
확인 후 다시 리뷰 요청 주세요

2022-07-17 02:24 UTC, laco-dev commented on app/src/androidTest/java/edu/nextstep/camp/calculator/MainActivityDisplayTest.kt
> +    }
테스트 환경에 대한 유틸 함수 좋습니다!

타입 추론과 infix 함수를 이용하면, 더욱 가독성을 올려볼 수 있을 것 같아요.
```kotlin
private fun clicks(vararg targets: Any) { ... }

private infix fun Any.shouldHaveText(expected: String) = checkDisplayText(expected)

// before
click(3)
click("+")
click(2)
click("=")

checkDisplayText(5)

-->

// after
clicks(3, "+", 2, "=") shouldHaveText "5"

```

2022-07-17 02:24 UTC, laco-dev commented on app/src/androidTest/java/edu/nextstep/camp/calculator/TestUtil.kt
> +internal fun isToast(): Matcher<Root> {
토스트 메시지 테스트 목적으로 추가된 Matcher 클래스 같은데, 사용이 되지 않아요.

토스트 테스느는 환경에 따라 제약사항이 많아서, 저는 개인적으로 테스트를 피하고는 하는데 사용하지 않는다면 삭제해주시면 될 것 같습니다.

2022-07-17 02:24 UTC, laco-dev commented on app/src/main/java/edu/nextstep/camp/calculator/CalculatorDisplayModel.kt
> +    val state get() = _state.joinToString(separator = " ")
이 객체를 보면서 `ViewModel`과 상당히 유사하다는 느낌을 받았습니다.

View에게 보여주기 위한 State를 공개하고, 내부적으로 비즈니스 로직을 수행하고 있습니다.
그런데 우리는 지난 단게에서 비즈니스 로직을 분리하기 위해 domain 모듈에 여러가지 객체를 만들어 왔는데요.

마찬가지로 ViewModel은 도메인 모델과 협력해서 결과를 받아오도록 하는게 좋겠습니다.

`CalculatorDisplayModel`에서 비즈니스 로직을 분리해서 domain 모듈에 추가하고.
(관련된 유닛 테스트가 따라와야 합니다)

이후 이 객체랑 협력을 해서 처리하도록 개선 해보세요.

2022-07-17 02:24 UTC, laco-dev commented on app/src/main/java/edu/nextstep/camp/calculator/CalculatorDisplayModel.kt
> +    private val calculator = Calculator()
계산할 때에만 한번 사용된다면 calculate()함수 에서만 생성해도 되지 않을까요?

2022-07-17 02:24 UTC, laco-dev commented on app/src/main/java/edu/nextstep/camp/calculator/CalculatorDisplayModel.kt
> +        require(number in 0..9) { "Invalid number $number, must be between 0 and 9." }
계산기 모델이 명확하게 1부터 9까지만 피연산자를 가진다면, Opearnd에서 이 책임을 가지도록 하면 어떨까요?

2022-07-17 02:24 UTC, laco-dev commented on app/src/main/java/edu/nextstep/camp/calculator/CalculatorDisplayModel.kt
> +    }
> 마지막 입력 값에 따라서 동작이 달라지니 그에 따라 EmptyState, OperandState, OperatorState 이런 식으로 구분하고 여기에서는 currentState에 대해서 put 하는 식으로 할까 했는데요. currentState를 갱신하는 쪽 코드가 난해하다고 생각이들어서... (delete 시점에는 이전 state에 대한 정보도 필요하는 등) 복잡해지더라고요. 어떤 식으로 풀어낼 수 있을지..


현재 CalculatorDisplayModel 구조상 가변적인 형태로 되어 있어 접근이 다소 어렵게 느껴지실 수 있습니다.

현재의 상태 기반으로 변경되는 개념을 구현하려면 추상화를 이용해 접근해야 할 것 같은데요.

```kotlin
abstract class State(value) {
   abstract fun put(...): State
   abstract fun delete(): State
   fun calculate(): State { ... }
}

class EmptyState: State {
   fun delete() { ... 아무것도 하지 않음 }
}

abstract class ExistsState(value): State {
   fun delete() { 만약 value 길이가 1이라면 EmptyState로 바꾸고 아니면 등등 }
}

class OperandState: ExistsState { ... }
class OperatorState: ExistsState { ... }
```

막연하게 떠오른 대로 글을 남겨보았는데,
이 과정까지 하기에는 객체지향의 개념이 많이 필요해서 이번 단계에서 상당히 많은 시간을 소요해야 할 수 있어요.

우선은 참고만 해 보시고 반영은 하지 않으셔도 됩니다.

2022-07-17 02:24 UTC, laco-dev commented on app/src/main/java/edu/nextstep/camp/calculator/CalculatorDisplayModel.kt
> +            }
한 줄로 사용되는 간단한 경우는 중괄호를 생략해서 작성하는 것이 좋습니다.
https://developer.android.com/kotlin/style-guide?hl=ko#braces

2022-07-17 02:24 UTC, laco-dev commented on app/src/main/java/edu/nextstep/camp/calculator/MainActivity.kt
> +                model.calculate()
아무것도 입력을 하지 않은 상태에서 "=" 버튼을 누르면 크래시가 나네요!

2022-07-17 02:24 UTC, laco-dev commented on app/src/main/java/edu/nextstep/camp/calculator/MainActivity.kt
> +    }
지난 단계에서 추가한 Token을 사용하지 않는 이유가 있을까요?
DisplayModel도 String이 아닌 Token을 가지고 관리를 하면 더욱 좋을 것 같습니다.

2022-07-17 03:10 UTC, greedy0110 commented on app/src/main/java/edu/nextstep/camp/calculator/MainActivity.kt
> +    }
MainActivity에서 Token을 만들어서 건내준다면, Calculator.evaluate의 인터페이스가 string인 이점이 사라지는 것 같습니다. 그런 생각으로 최초에 internal로 토큰을 개발했었는데요.

UI에서 이미 Token의 존재를 알고 생성할 수 있다면 인터페이스의 수정이 필요할까 싶네요.

1. UI에서 간단한 char로 신호를 쏨 (MainActivity)
2. Token으로 가공하고 Token 리스트 관리 (CalculatorDisplayModel)
3. Calculator는 Tokenizer를 거치지 않고 그냥 parsing하는 evaluate 인터페이스 제공 (Calculator)

그렇지 않으면 

1. UI에서 Token 생성
2. CalculatorDisplayModel 에서 Token 리스트 관리, string으로 변환해서 UI에 feed, Calculator에 feed
3. Calculator가 원래는 Token 리스트였던 feed된 문자열을 받아서 다시 Tokenize

2022-07-17 05:08 UTC, greedy0110 commented on domain/src/main/java/edu/nextstep/camp/calculator/domain/CalculatorDisplayModel.kt
> +class CalculatorDisplayModel {
토큰 생성의 책임을 가집니다.

2022-07-17 05:09 UTC, greedy0110 commented on domain/src/main/java/edu/nextstep/camp/calculator/domain/Calculator.kt
> +    internal fun evaluate(tokens: List<Token>): Int {
임의의 expression에 대한 연산을 제공하지 않습니다. 정제된 Token 리스트만 입력으로 받습니다. Parsing하는 과정에서 Token 순서에 문제가 있으면 에러를 발생합니다.

2022-07-17 06:01 UTC, laco-dev requested changes
피드백 잘 반영 해주셨습니다.

마지막 단계인 만큼, 조금 더 개선 해 보면 좋을 만한 내용을 같이 남겼습니다. 🙏🏻

2022-07-17 06:01 UTC, laco-dev commented on domain/src/main/java/edu/nextstep/camp/calculator/domain/Calculator.kt
> +    internal fun evaluate(tokens: List<Token>): Int {
Calculator로부터 String을 파싱하고 변환하는 의존성을 잘 분리 해주셨네요.

그렇다면 한번 더 분리해서 Calculator가 Expression을 받아서 Expression을 반환하도록 하면 어떨까요?

결과적으로 "식"을 입력받아 "식(값)'을 반환하는 단일 책임으로 볼 수 있고,
Token에 대한 관리 책임을 DisplayModel로 집중 할 수 있을 것 같습니다.

```kotlin
internal fun evaluate(expression: Expression): Expression = ValueNode(expression.evaluate())
```

2022-07-17 06:01 UTC, laco-dev commented on domain/src/main/java/edu/nextstep/camp/calculator/domain/CalculatorDisplayModel.kt
> +        )
UI가 어떻게 노출될지를 도메인 로직에 작성하는 것이 살짝 아쉽네요.
만약 클라이언트 (UI)의 요구사항이 변경되면 도메인 비즈니스 로직이 변경되야 합니다.

출력 로직 자체를 확실하게 비즈니스 로직으로 판단하신다면,
Token이 아닌 Expression의 책임으로 만들어 보면 어떨까요?

가령 Expression(2, "+", 3)의 `toString()`은 "2 + 3" 이라고 출력할 수 있을 것 같습니다.
```kotlin
ValueNode(2) --> "2"
ExpressionNode(ValueNode(2), ValueNode(3), Operator.Plus) --> "2 + 3"
```

2022-07-17 06:01 UTC, laco-dev commented on domain/src/main/java/edu/nextstep/camp/calculator/domain/CalculatorDisplayModel.kt
> +        }
token가 더이상 BackingProperty로 활용되지 않아서 `_tokens` 대신 바로 `tokens`로 만들어도 될 것 같습니다.

2022-07-17 06:01 UTC, laco-dev commented on domain/src/main/java/edu/nextstep/camp/calculator/domain/CalculatorDisplayModel.kt
> +            }
if, else구문이 중괄호로 나눠지는 경우 if 구문도 항상 중괄호를 열어 주어야 합니다.

https://developer.android.com/kotlin/style-guide?hl=ko#expressions

2022-07-17 06:05 UTC, laco-dev commented on app/src/main/java/edu/nextstep/camp/calculator/MainActivity.kt
> +    }
네, 말씀주신 부분도 공감이 됩니다.

다만 인터페이스 제공자로 바라본다면 `Calculator.evaluate(string)` 이라는 인터페이스가 어떻게 동작할 것이라는 것이 예측이 될까요?

어떻게 문자열을 넣어야 하는지, 어떤 규칙이 있는지 등 정보가 없기 때문에 실수를 유발할 수 있습니다.
그렇기에 계산기의 인터페이스가 의도한대로 동작하기 위해 Token으로 강제하는 이점은 충분히 많다고 봅니다.

만약 이름이 너무 일반적이라면 `StringCalculator` TokenCalculator` 등의 네이밍으로 변경할 수도 있습니다.

2022-07-17 07:52 UTC, greedy0110 commented on domain/src/main/java/edu/nextstep/camp/calculator/domain/Calculator.kt
> +    internal fun evaluate(tokens: List<Token>): Int {
그렇게 되면 Calculator 자체가 의미가 없는 듯 하네요? Expression에서 이미 계산에 관련된 모든 책임을 다합니다

2022-07-17 08:05 UTC, greedy0110 commented
이렇게 정리가 되네요.

- CalculatorDisplayModel: 사용자 입력을 받는 interface 제공, Token 리스트 생성의 책임
- Parser: Token 리스트로부터 Expression을 추출하는 책임
- Expression: 식을 계산하는 책임

2022-07-17 12:51 UTC, laco-dev approved these changes
피드백 잘 반영 해 주셨습니다. 🙏🏻 

계산기가 간단한 도메인이라 할지라도 구현 방법은 모두가 다르다는게 새로우면서도 저도 같이 성장하는 기회가 된 것 같습니다.

이번 미션에서는 Expression이 계산에 대한 책임을 같이 수행하도록 구현 해 보았다면,
2주차 이후에서는 Expression은 표현식만을 가지도록 하고, 계산기는 계산에 대한 책임만 수행하도록 만들어 보셔도 좋습니다.,

그동안 잘 따라와주셔서 감사합니다.
1단계 미션은 종료하겠습니다

2022-07-17 12:52 UTC, merged