🚀 4단계 - 계산기 UI
next-step/android-calculator-mvc pull request #155
Opened 2022-07-16 14:42 UTC by Jaesungchi

안녕하세요 영직님!!! ㅎㅎㅎㅎㅎ

4단계 미션 완료해서 PR드립니다~! 잘부탁드립니다!!! (_ _)

2022-07-17 02:55 UTC, laco-dev requested changes
4단계 빠르게 진행 해 주셨네요.

MVC에서는 액티비티가 컨트롤러 역할을 같이 수행합니다.
그렇기에 우리는 지난 단계까지 해서 도메인 모델을 분리하는 연습을 해 보았는데요.
마찬가지로 계산 기록과 처리하는 로직을 도메인 모델로 분리하고 컨트롤러가 협력 관계로 구현을 할 수 있도록 만들어보세요. 🙏🏻

2022-07-17 02:55 UTC, laco-dev commented on app/src/androidTest/java/edu/nextstep/camp/calculator/MainActivityTest.kt
> +        // when : 8 이 적혀있는 상태에서 9버튼을 누르면
"8이 적혀있는 상태에서" 라는 표현을 테스트 동작에서는 `given`으로 나타냅니다.

```kotlin
// given : 8이 적혀있는 상태에서

// when : 9 버튼을 누르면

// then : ....
```

2022-07-17 02:55 UTC, laco-dev commented on app/src/androidTest/java/edu/nextstep/camp/calculator/MainActivityTest.kt
> +        onView(withId(R.id.buttonDelete)).perform(click())
테스트코드에 대한 가독성을 올리는 것도 좋은 리팩토링 방법입니다.

```kotlin
clicks(button3, button2, buttonPlus, button1, buttonDelete)
```
위 처럼 표현할 수도 있고... 약간 오버엔지니어링을 해본다면 아래처럼 작성할 수도 있어요.
참고만 해주세요!
```kotlin
clicks(3, 2, "+", 1, "<") shouldHaveText "32 +"
```

2022-07-17 02:55 UTC, laco-dev commented on app/src/main/java/edu/nextstep/camp/calculator/MainActivity.kt
> +        }
resultText가 UI에 표현하기 위한 값을 담고 있다보니,
마지막 문자를 지워주는 등의 추가적인 로직이 필요하게 되었는데요.

적절한 자료구조를 이용해 Operand과 Operator를 가지고있게 만들고 UI 에서 보여주기 위한 로직을 별도로 작성 해 보면 어떨까요?

2022-07-17 02:55 UTC, laco-dev commented on app/src/main/java/edu/nextstep/camp/calculator/MainActivity.kt
> +    }
지난 단계까지를 통해 우리는 계산을 하려는 비즈니스 로직을 domain 모듈로 분리를 했습니다.
마찬가지로 현재 액티비티에 도메인 로직이 많이 포함되어 있는데 

계산 기록과 결과를 처리하는 도메인 모델을 분리해서 만들어 보면 좋겠습니다.
(관련해서 테스트도 같이 따라와야 합니다.)

2022-07-18 23:11 UTC, laco-dev requested changes
좋습니다. 👍🏻 

Model 역할이 액티비티에서 분리되어서 보다 좋은 구조가 되었네요.
대신 Calculator의 책임이 늘어나게 되었는데, 이 역할을 하는 별도 객체를 만들 수 있도록 피드백을 드려 보았습니다.

2022-07-18 23:11 UTC, laco-dev commented on domain/src/main/java/edu/nextstep/camp/calculator/domain/Calculator.kt
> +        get() = _expressionStack.joinToString(delimiter.toString())
Calculator는 계산하는 단일 책임을 잘 수행하고 있었는데,
계산을 기록하고 표현식을 관리하는 책임까지 가지게 되었습니다.

이번에 추가된 계산 기록을 관리하는 개체를 별도로 분리하고, 계산기와 협력하도록 만들면 어떨까요?

2022-07-18 23:11 UTC, laco-dev commented on domain/src/main/java/edu/nextstep/camp/calculator/domain/Calculator.kt
> +    private val _expressionStack = Stack<String>()
expressionStack은 BackingProperty로 활용되지 않기 때문에 `_XXX` 형태로 작성할 필요가 없는 것 같습니다.

2022-07-18 23:11 UTC, laco-dev commented on domain/src/main/java/edu/nextstep/camp/calculator/domain/Calculator.kt
> +        require(expression.isNotBlank()) { IllegalArgumentException(IS_NULL_OR_BLANK) }
onError를 이용해, 함수 내부에서 발생하는 예외를 전달하도록 만들었는데
실제로는 require를 이용해 런타임 오류가 발생할 수 있습니다.

모두 예외를 터트리거나 onError로 전파하거나 둘 중 하나로 사용해야 할 것 같습니다.

2022-07-19 04:49 UTC, Jaesungchi commented on domain/src/main/java/edu/nextstep/camp/calculator/domain/Calculator.kt
> +        require(expression.isNotBlank()) { IllegalArgumentException(IS_NULL_OR_BLANK) }
헛 요부분, 기록을 관리하는 부분을 분리해서 onError가아닌 onShowErrorToast로 에러 토스트를 띄우는 네이밍으로 변경했습니다!

2022-07-19 11:23 UTC, laco-dev requested changes
피드백 반영 확인 했습니다. 🙏🏻 

도메인 로직에서 UI의 관심사를 끌어들이게 되어서, 한 가지 피드백을 추가로 남겨드렸는데요.
마지막 단계인만큼 해결 해보면 좋겠습니다. 💪🏻

2022-07-19 11:23 UTC, laco-dev commented on domain/src/test/java/edu/nextstep/camp/calculator/domain/CalculatorTest.kt
> +        assertEquals(calculator.evaluate(expression), answer)
ParameterizedTest를 이용한 가독성 개선 👍🏻

2022-07-19 11:23 UTC, laco-dev commented on domain/src/main/java/edu/nextstep/camp/calculator/domain/Expression.kt
> +    fun evaluate(onShowErrorToast: (() -> Unit)? = null) {
토스를 보여준다는 라는 행위는, 이 함수를 호출하는 곳의 관심사가 아닐까요?

가령 토스트가 아닌 로그를 출력하거나, 다른 결과를 UI로 보여주거나 한다면 도메인 로직이 변경이 되야 합니다.

논리적인 오류라면 명확한 오류 타입을 만들어서 예외를 발생 시키는 방법이 있습니다.

```kotlin
if (expression.isEmpty() || ...) {
   throw ExpressionEmptyException(...)
}
```

추가로, 마이너한 의견인데 고차 함수를 이용하면 코틀린에서의 가독성 편의성을 올릴  수 있지만, 이 코드를 사용하는 곳에서는 성공한 람다인지 실패한 람다인지를 구분하기가 다소 어렵기도 합니다.
(이 내용은 반영하지 않으셔도 됩니다.)

```kotlin
// caller
expression.evaluate { 여기는 성공한 람다인지?, 실패한 람다인지? 실제 코드를 들어가보지 않으면 모름 }

// 보통은 이런 형태로 많이 사용이 되거나
expression.evalute(
   onSuccess = { result -> ... },
   onError = { showToast(...) }
)

// Result를 이용하기도 함
val result: Result<Int> = expression.evalute()

fun evaluate(): Result<Int> { ... }
```

2022-07-19 11:38 UTC, Jaesungchi commented on domain/src/main/java/edu/nextstep/camp/calculator/domain/Expression.kt
> +    fun evaluate(onShowErrorToast: (() -> Unit)? = null) {
오우 위에 방법은 생각도 못했네요ㅎㅎ;; 실무하면서 throw를 던져서 받아서 처리할일이 없어서 낯설게 느꼈나 봅니다 ㅎㅎ

2022-07-19 11:39 UTC, laco-prnd approved these changes
앗..

2022-07-19 11:42 UTC, laco-dev approved these changes
도전 해볼만한 내용을 많이 요구드린 것 같은데, 잘 따라와 주셔서 감사합니다.
이번 단계에서 배운 경험을 다음 미션에서도 잘 활용 해 볼 수 있도록 하세요.

그동안 고생하셨습니다. 👍

2022-07-19 11:42 UTC, merged