Step4 계산기 UI
next-step/android-calculator-mvc pull request #183
Opened 2022-07-21 07:01 UTC by AnKyungMoo

step4 계산기 UI 리뷰 요청합니다!

step3때 리뷰 많이 해주셔서 도움이 많이 되었습니다 ㅎㅎ
이번에도 잘부탁드립니다

2022-07-21 16:13 UTC, namjackson requested changes
안녕하세요 4단계 미션 고생하셨습니다!
몇가지 의견 코맨트로 남겼으니, 확인해주세요! 
변경사항 적용 후, 다시 리뷰요청해주시면 감사하겠습니다 😄

2022-07-21 16:13 UTC, namjackson commented on app/src/main/java/edu/nextstep/camp/calculator/MainActivity.kt
>  class MainActivity : AppCompatActivity() {
과제 요구사항에 UI 테스트도 포함되어있어요! 
변경된 MainActivity의 UI 테스트를 작성해주세요!

2022-07-21 16:13 UTC, namjackson commented on app/src/main/java/edu/nextstep/camp/calculator/MainActivity.kt
> +    }
해당 버튼의 text를 input함수의 파라미터로 호출한 후, 
editor클래스 내에서 각 로직을 분기처리 해주는 방식은 어떨까요?
불필요한 activity 중복코드도 제거할수 있고,
View에서 모델의 로직을 조금더 분리해줄수 있을거같아요!

2022-07-21 16:13 UTC, namjackson commented on app/src/main/java/edu/nextstep/camp/calculator/MainActivity.kt
> +        if (editor.isEnableCalculateExpression()) {
```
if (editor.isEnableCalculateExpression()) {
  Toast.makeText(this@MainActivity, "완성되지 않은 수식입니다", Toast.LENGTH_SHORT).show()
  return
}
..로직..
```
이런 방식은 어떨까요? 예외처리와 중요로직을 조금 더 직관적으로 표현할수 있을거같아요!

2022-07-21 16:13 UTC, namjackson commented on domain/src/main/java/edu/nextstep/calculator/domain/Editor.kt
> +class Editor {
Editor는 조금 UI같은 네이밍인거같아요.
필수로 적용하진 않으셔도 되긴하지만, 개인적인 의견으로는 
"클래스가 무슨 역할을 수행하는지"를 조금 더 명확하게 표현해주면 좋을거같아요
이 클래스는 Expression를 관리해주고, 처리해주는 역할을 책임지고 있는거 같은데요
ExpressionXXXX와 같은 네이밍은 어떨까요?

2022-07-21 16:13 UTC, namjackson commented on domain/src/main/java/edu/nextstep/calculator/domain/Editor.kt
> +        }
두개 이상의 조건문일 경우, if else보단 when문을 활용하는 것이 좋습니다!

또 해당 함수에 불필요하게 중복되는 로직이 상당히 많이 보이는데요,
```
ExpressionValidator.isNumber(content)
getExpressionLast, expressionContents.last()
```
함수내 로직을 정리해주시면 좋을거같아요!

2022-07-21 16:13 UTC, namjackson commented on domain/src/main/java/edu/nextstep/calculator/domain/Editor.kt
> +    private fun getExpressionLast(): String? {
같은 기능을 하는 lastOrNull 이라는 익스텐션함수가 존재해요!

2022-07-21 16:13 UTC, namjackson commented on domain/src/main/java/edu/nextstep/calculator/domain/Editor.kt
> +        }
마찬가지로, 두개의 if문을 하나의 when문으로 정리해주시면 좋을거같아요!

2022-07-21 16:13 UTC, namjackson commented on domain/src/main/java/edu/nextstep/calculator/domain/Editor.kt
> +    fun getExpression(): String {
같은 기능을 하는 익스텐슨 함수가 존재합니다
`joinToString`

2022-07-21 16:13 UTC, namjackson commented on domain/src/main/java/edu/nextstep/calculator/domain/Editor.kt
> +    fun resetExpression(content: String?) {
지금은 content의 값이 하나의 단위만 고려한거같아요!
reset이라면 여러 복잡한 연산식의 문자열도 입력할수 있지않을까요?

만약 그렇다면, content 문자열 검증도 필요할거 같아요

2022-07-21 16:13 UTC, namjackson commented on domain/src/main/java/edu/nextstep/calculator/domain/Editor.kt
> +        }
when문으로 변경해주세요! 
추가로 last(), removeLast() 은 Exception이 발생할수 있어요 
안전한 `removeLastOrNull, lastOrNull` 를 사용하는 방법도 좋습니다

2022-07-21 16:13 UTC, namjackson commented on domain/src/test/kotlin/edu/nextstep/calculator/domain/EditorTest.kt
> +    @ParameterizedTest
ParameterizedTest 활용 👍

2022-07-22 06:29 UTC, AnKyungMoo commented on domain/src/main/java/edu/nextstep/calculator/domain/Editor.kt
> +        }
이 두개의 if문은 각자 존재해야지 로직이 돌아갑니다.
첫번째 if문은 현재 입력되어있는 수식의 마지막이 연산자라면 마지막 연산자를 삭제합니다.
그리고 그 뒤에 수식이 비어있지 않다면 연산자를 추가하려고 하는데요

만약 when을 이용하게 된다면 
1. 수식의 마지막이 연산자일 때 삭제 후 추가
2. 수식이 비어있지 않으면 추가

의 형태로 생각이 됩니다.
그러면 추가하는 코드가 반복되어 두번이 들어가게 되어 if문을 두개로 분리하였어요.

또한 두개의 if식은 서로 연관이 없습니다.
하나는 현재 가지고 있는 수식의 마지막이 연산자인지, 하나는 수식이 비어있는지를 체크하는 것이기 때문에 when으로 묶지 않고 if식으로 처리하였습니다.

이런 경우에 when으로 변경하려면 어떤 형식으로 변경해야하는지 궁금합니다.

2022-07-22 06:41 UTC, AnKyungMoo commented on domain/src/main/java/edu/nextstep/calculator/domain/Editor.kt
> +        }
저는 한 객체의 state를 나눌때와 같이 의미상 묶이는 것이 있을 때 자주 사용하곤합니다.
지금의 케이스와 같이 특정 객체를 묶기도 어렵고, 이럴때는 오히려 if식이 더 직관적이라고 생각하고 있어서요

물론 현재는 비슷한 구절이라 묶었을 때 깔끔해보일 수 있긴 하지만.. when(내용) 처럼 내용으로 묶을 수 있지는 않아서요

리뷰어님께서는 어떨 때 if식과 when식을 나누시는지, 여기서는 왜 when을 추천하셨는지 궁금합니다.

2022-07-22 09:05 UTC, AnKyungMoo commented on domain/src/main/java/edu/nextstep/calculator/domain/Editor.kt
> +        }
https://github.com/next-step/android-calculator-mvc/pull/183#discussion_r927330832
여기 질문과 동일합니다..!

2022-07-22 16:34 UTC, namjackson requested changes
몇가지 코멘트 및 질문에 대한 답변을 리뷰로 남겼습니다!
참고해주세요!

2022-07-22 16:34 UTC, namjackson commented on domain/src/main/java/edu/nextstep/calculator/domain/ExpressionManager.kt
> +    fun input(operator: Operator) {
외부에서 사용하지 않는 함수는 private를 기본으로 해주세요! 

함수가 하는일에 따라 함수명을 조금 더 명확하게 변경해주세요! 
Operator가 추가되는 함수입니다!  Operator가 추가된 함수명을 작성해주시면 어떨까요?

2022-07-22 16:34 UTC, namjackson commented on domain/src/main/java/edu/nextstep/calculator/domain/ExpressionManager.kt
> +        }
현재 이 함수를 나눠보면 어떨까요?
이 함수에는 들어온 content를 분기처리 역할과, numberOperand를 추가하는 역할 
두가지 역할의 책임이 있는거 같아요!

2022-07-22 16:34 UTC, namjackson commented on domain/src/main/java/edu/nextstep/calculator/domain/ExpressionManager.kt
> +        if (isNumberByContent && isNumberByExpressionContentLast.not()) {
위의 코멘트 내용대로 number의 경우에만 해당하는 함수를 분리한다면 
`isNumberByContent` 조건은 불필요해질거 같아요!

2022-07-22 16:34 UTC, namjackson commented on domain/src/main/java/edu/nextstep/calculator/domain/ExpressionManager.kt
> +        }
(이전 질문에 대한 답변입니다)

좋은 질문주셨습니다! 😄 
경무님이 생각하는 좋은 코드란 무엇일까요?  
코딩에는 다양한 방식이 있어서, 항상 정답은 없습니다! (아래의 내용은 저의 개인적인 의견으로 들어주시면 좋을거같아요 )
좋은 코드에 대한 많은 의견이 있지만, 많은 공감을 하는 내용중 하나는 "읽기 좋은 코드" 인데요!
먼저 if조건문 여러 조건(&&,||)이 함께 들어가 있으면, 가독성이 매우 나빠집니다.  
이번 수정에서는 변수를 이용해 가독성 높여주셨지만, 위의 코멘트처럼 불필요한 조건을 제거해주시면 더 깔끔해질것같아요!

이 메소드의 역할을 고민해보시면 좋을거같아요! 
Number로 입력받은 값을 표현식 마지막 값의 상태에 따라 입력해주는 역할을 하고있는데요,
 
```kotlin
val lastContent = expressionContents.lastOrNull()
when {
    lastContent == "0" -> {
        expressionContents.removeLastOrNull()
        expressionContents.add(content)
    }
    ExpressionValidator.isNumber(lastContent) -> {
        expressionContents.removeLastOrNull()
        expressionContents.add(lastContent.plus(content))
    }
    else -> {
        expressionContents.add(content)
    }
}
```
저라면 이런식으로 코드를 작성할거같아요. 
경무님 말씀대로, 추가하는 코드가 반복되어 두번 들어가는 단점이 있지만,
마지막 문자열의 State에 따라 관리할 수 있어 직관적이라는 장점도 있다고 생각합니다!

상수, extention함수등을 활용하면 더 가독성있는 코드를 작성할수 있습니다
```kotlin
when {
    lastContent.isZero() -> ..
    lastContent.isNumber() -> ..
    else -> 
}

private fun String?.isOperator() = ExpressionValidator.isOperator(this)
private fun String?.isNumber() = ExpressionValidator.isNumber(this)
private fun String?.isZero() = this == ZERO
```
추가로 expressionContents을 String이 아닌 객체로 정의해서 활용하면 더 가독성이 좋을수 있습니다!
```kotlin
when(lastContent) {
    is ZERO -> ..
    is NumberOperand -> ..
    is Operator ->..
    else -> ..
}
```

추가로 코틀린 코딩 컨벤션에 if vs when에 대한 내용인데요,
if, else if 로 된 코드는 2개의 조건처럼 보이지만, 아무것도 하지않는 else문을 생략한 3개의 조건문으로 보여지는데요,
코틀린 공식 컨벤션에서는
이진 조건일 경우, if문을 활용을 추천하지만, 3개 이상이 넘어가는 코드에는 when의 사용을 추천하고 있습니다.  
https://kotlinlang.org/docs/coding-conventions.html#if-versus-when
컨벤션은 개발자들 끼리의 하나의 약속인데요, 잘 지켜주시면 개발자들 끼리의 코드 이해도가 높아질것 같아요!

2022-07-22 16:34 UTC, namjackson commented on domain/src/main/java/edu/nextstep/calculator/domain/ExpressionManager.kt
> +        }
erase 과정에서 고려해볼법한 부분이 한가지 더있는데요!
"1 - 2 =" 결과가 "-1"을 작성한 후, erase를 실행하면 "-"가 남게되어, 
다음연산시 크래시가 발생하는 버그가 존재합니다! 
(음수의 영역은 요구사항이 아니라서, 필수로 적용하진않으셔도 됩니다) 

개인적으로는 각각의 Expression의 문자열이 아닌 객체로 정의하여 관리하는 방법을 활용해도 좋을거 같습니다!

2022-07-22 16:34 UTC, namjackson commented on app/src/androidTest/java/edu/nextstep/camp/calculator/MainActivityTest.kt
> +        onView(withId(R.id.textView)).check(matches(ViewMatchers.withText("212")))
중복되는 기능을 함수로 분리하면, 조금 더 가독성있는 코드를 작성할 수 있습니다.
```
fun `버튼을 누른다`(id:Int) {
  onView(withId(id)).perform(click())
}
```
(필수로 적용하지 않으셔도 괜찮습니다)

2022-07-22 16:34 UTC, namjackson commented on domain/src/test/kotlin/edu/nextstep/calculator/domain/ExpressionManagerTest.kt
> +        val operator = Operator.fromValue(content) ?: return
` ?: return`를 사용하면, 중간에 exit되어 검증이 진행되지 않아요!
현재는 ValueSource가 틀림없는 Operator라 그럴 일이 없지만,

기존 코드가 변하더라도, 테스트 코드의 검증은 동작해야하므로, 좋은 방법이 아닐꺼같아요. 
null로 나오면 테스트 실패가 되도록 변경해주세요!

2022-07-22 16:34 UTC, namjackson commented on domain/src/test/kotlin/edu/nextstep/calculator/domain/ExpressionManagerTest.kt
> +        val operator = Operator.fromValue(content) ?: return
Operator 클래스에 대한 테스트 코드가 없네요! 
추가로 작성해주시면 좋을거같아요!

2022-07-23 09:25 UTC, AnKyungMoo commented on domain/src/test/kotlin/edu/nextstep/calculator/domain/ExpressionManagerTest.kt
> +        val operator = Operator.fromValue(content) ?: return
OperatorTest 코드 있습니다!

2022-07-23 16:48 UTC, namjackson approved these changes
4단계 미션은 종료하겠습니다,
피드백 반영해주시느냐 고생하셨습니다!
다른 미션들도 응원하겠습니다 😄

2022-07-23 16:48 UTC, namjackson commented on app/src/androidTest/java/edu/nextstep/camp/calculator/MainActivityTest.kt
>          onView(withId(R.id.textView)).check(matches(ViewMatchers.withText("9 /")))
기회가 되시면, 버튼 클릭외에도 
`문자을_확인한다` 와 같은 함수로 분리해도 좋을거같아요!

2022-07-23 16:48 UTC, namjackson commented on domain/src/main/java/edu/nextstep/calculator/domain/ExpressionManager.kt
> +            true -> {
커뮤니케이션에 미스가 있있던것 같네요 🙏 

메소드가 분리되면서, 조건문이 간결해졌는데,
조건문이 if문 하나로 가능할때는, 굳이 when문을 사용하지 않으셔도 좋을거 같네요ㅠㅠ!

2022-07-23 16:49 UTC, merged

2022-07-23 16:51 UTC, namjackson commented
1주차 미션 고생하셨습니다!
리뷰과정을 통해 저 또한 많이 배울 수 있었던것 같아요. 👍 
1주차 과제과정이 의미있는 시간이 되셨으면 좋겠습니다.
한 주간 감사했습니다!
이후 미션들도 완주하길 응원할게요! 화이팅! 😸

2022-07-23 18:14 UTC, AnKyungMoo commented
1주차 미션 진행하면서 리뷰어님 덕분에 많은 것을 배웠습니다ㅎㅎ
꼼꼼하게 리뷰해주시고 질문에 열심히 답변해주셔서 감사드려요!
고생하셨습니다!!