step3 문자열 계산기
next-step/android-calculator-mvc pull request #76
Opened 2022-01-20 10:31 UTC by chohohee

step3 진행된 부분 리뷰 요청드립니다!

2022-01-20 13:38 UTC, BeokBeok requested changes
이전 단계 피드백과 문자열 계산기 미션 하시느라 고생하셨습니다 👍 
고민해볼만한 의견들을 코맨트로 작성하였으니, 충분히 고민해보시고 도전해보세요 💪

2022-01-20 13:38 UTC, BeokBeok commented on app/src/main/java/edu/nextstep/camp/calculator/MainActivity.kt
> +    fun onData() {
onData 라는 함수명만 보았을 때, 이 함수가 어떤 일을 하는지 짐작이 어렵습니다.
또한, 앞에 on prefix가 붙었다는 것은 콜백을 의미하는 것 같은데 실제로 콜백도 아니네요.
이 함수가 하는 일에 대해서 좀 더 구체적으로 작성해보면 어떨까요?

2022-01-20 13:38 UTC, BeokBeok commented on domain/src/main/java/edu/nextstep/camp/calculator/domain/Calculator.kt
> +    }
하나의 함수에서 두 가지 이상의 일을 하고 있네요 (수식 분리, 연산 등)
프로그래밍 요구사항 중 `메서드가 너무 많은 일을 하지 않도록 분리하기 위해 노력해 본다.`을 만족하도록 하나의 일만 하도록 함수를 분리해보면 어떨까요?

2022-01-20 13:38 UTC, BeokBeok commented on domain/src/main/java/edu/nextstep/camp/calculator/domain/Calculator.kt
> +                    }
서로 관련있는 상수들의 집합일 경우에는 enum을 활용해주시면 좋습니다.

ref. https://kotlinlang.org/docs/enum-classes.html#anonymous-classes

2022-01-20 13:38 UTC, BeokBeok commented on domain/src/test/java/edu/nextstep/camp/calculator/domain/CalculatorTest.kt
> +    fun `두 수를 더하면 정답이 나와야 한다`() {
정답이라는 말은 과연 어떤 것을 의미할까요?
1+1을 했을 때 3도 정답일까요?
테스트를 하고자하는 바를 좀 더 명확하게 작성해보면 좋을 것 같아요.

2022-01-20 13:38 UTC, BeokBeok commented on domain/src/test/java/edu/nextstep/camp/calculator/domain/CalculatorTest.kt
> +    }
에러 관련해서는 Assertion.assertThatXXXException과 같은 것을 활용해서 체크하는 것을 권장해요.

2022-01-20 23:42 UTC, chohohee commented on app/src/main/java/edu/nextstep/camp/calculator/MainActivity.kt
> +    fun onData() {
습관적으로 on### 메서드로 초기화를 해주었는데 콜백이라는 의미가 있는줄 몰랐네요..!

레이아웃의 초기 셋팅을 의미하는 initLayout 으로 수정해보았습니다 :D

2022-01-21 00:07 UTC, chohohee commented on domain/src/main/java/edu/nextstep/camp/calculator/domain/Calculator.kt
> +    }
연산하는 부분과 수식을 구하는 부분을 함수로 분리해보았습니다.

2022-01-21 00:09 UTC, chohohee commented on domain/src/main/java/edu/nextstep/camp/calculator/domain/Calculator.kt
> +                    }
별도 상수 클래스 생성해서 적용해보았습니다.

2022-01-21 00:15 UTC, chohohee commented on domain/src/test/java/edu/nextstep/camp/calculator/domain/CalculatorTest.kt
> +    fun `두 수를 더하면 정답이 나와야 한다`() {
정답이라는 표현이 모호한것 같긴하네요 🤔

좀 더 구체적으로 적어보았습니다. :D

2022-01-21 01:31 UTC, chohohee commented on domain/src/test/java/edu/nextstep/camp/calculator/domain/CalculatorTest.kt
> +    }
assertThrows 방식이 있어서 참고해서 수정해보았습니다. :D

2022-01-21 02:14 UTC, chohohee commented
피드백 반영해서 커밋 해두었습니다 :D

2022-01-21 13:00 UTC, BeokBeok requested changes
피드백 반영하시느라 고생하셨습니다 👍 
추가로 고민해볼만한 의견들을 코맨트로 작성하였으니, 충분히 고민해보시고 도전해보세요 💪

2022-01-21 13:00 UTC, BeokBeok commented on domain/src/main/java/edu/nextstep/camp/calculator/domain/Calculator.kt
> +    }
객체는 하나의 책임만을 담당해야 합니다. (SRP)
하지만 Cacluator 객체에서 실제로 Operator 객체의 책임까지 지고 있네요.

이 로직들은 Operator에서 처리해주시면 좋을 것 같아요.

ref. https://kotlinlang.org/docs/coding-conventions.html#wrap-chained-calls
ref. https://kotlinlang.org/docs/coding-conventions.html#wrap-chained-calls

2022-01-21 13:00 UTC, BeokBeok commented on domain/src/main/java/edu/nextstep/camp/calculator/domain/Calculator.kt
> +    private var operator = Operator.NONE
멤버 변수가 있으면, 멤버 변수의 상태에 따라 동일한 input이여도 output이 다르게 됩니다.
이는 특정 함수의 호출에 따라 테스트 결과가 달라지게 되는 등, 테스트 하기가 어려워집니다.

어려우시겠지만, 멤버 변수를 사용하지 않고 요구사항을 구현해보면 어떨까요?

2022-01-21 13:00 UTC, BeokBeok commented on domain/src/main/java/edu/nextstep/camp/calculator/domain/Calculator.kt
> +class Calculator {
하나 이상의 생성자가 없다면, class보다는 object 사용을 권장합니다.
클래스는 반드시 하나 이상 캡슐화를 하는 것을 권장합니다.

2022-01-21 13:00 UTC, BeokBeok commented on domain/src/test/java/edu/nextstep/camp/calculator/domain/CalculatorTest.kt
> +    fun `두 수를 더하면 더한 값이 나와야 한다`() {
더한 값이 나온다는 것은 어떤 값이 나오는 것일까요?
좀 더 구체적으로 작성해주시면 좋을 것 같아요.

가령, 5와 2를 더하면 7이 나옵니다 와 같이 명시적으로 적혀있으면 굳이 코드를 보지 않아도 함수명만 봐도 로직을 이해하기 편합니다.
(이하 관련 내용 동일)

2022-01-21 13:00 UTC, BeokBeok commented on domain/src/test/java/edu/nextstep/camp/calculator/domain/CalculatorTest.kt
> +    fun `입력된 값이 없으면 오류가 난다`() {
어떤 오류가 나는지 함수명에 명시되면 좋을 것 같아요.

2022-01-21 13:00 UTC, BeokBeok commented on domain/src/test/java/edu/nextstep/camp/calculator/domain/CalculatorTest.kt
> +        assertThat(exception.message).isEqualTo("exception data")
assertThat은 없고 assertThrows만 있어도 좋을 것 같아요. (이하 관련 내용 동일)

2022-01-22 13:41 UTC, chohohee commented on domain/src/main/java/edu/nextstep/camp/calculator/domain/Calculator.kt
> +    }
Operator 에서 사용되어야 할 로직들을 분리해보았습니다.

위 레퍼런스 wrap-chained-calls 은 로직의 어떤 부분에 적용해야하는지 이해가 잘 되지 않아서 적용해보진 못했습니다 😢

2022-01-22 13:43 UTC, chohohee commented on domain/src/main/java/edu/nextstep/camp/calculator/domain/Calculator.kt
> +    private var operator = Operator.NONE
편의상 사용하다보니 변수에 대해 고려하지 못했던것 같습니다.

로직을 분리하면서 호출된 함수에서 정의되도록 수정해보았습니다!

2022-01-22 13:47 UTC, chohohee commented on domain/src/main/java/edu/nextstep/camp/calculator/domain/Calculator.kt
> +class Calculator {
object 로 선언하면서 싱글턴 객체가 되는 건 이해가 되었습니다.

혹시 하나 이상의 캡슐화라는 것은 object 를 선언함으로 써 캡슐화가 된다는 의미일까요?

2022-01-22 13:49 UTC, chohohee commented on domain/src/test/java/edu/nextstep/camp/calculator/domain/CalculatorTest.kt
> +    fun `입력된 값이 없으면 오류가 난다`() {
구체적으로 exception 을 명시하였습니다.

2022-01-22 13:50 UTC, chohohee commented on domain/src/test/java/edu/nextstep/camp/calculator/domain/CalculatorTest.kt
> +        assertThat(exception.message).isEqualTo("exception data")
exception 메세지도 일치해야 된다고 생각을 하였는데 메세지는 부가적인 부분이고 핵심인 exception 상황으로 테스트는 확인되는 것인가 보군요!

2022-01-22 13:51 UTC, chohohee commented
위 피드백 사항 반영하여 커밋해두었습니다 :D

2022-01-23 05:43 UTC, BeokBeok commented on domain/src/main/java/edu/nextstep/camp/calculator/domain/Calculator.kt
> +    }
레퍼런스 복사가 잘못되었네요 😭 
링크 수정해두었습니다 🙏

2022-01-23 05:44 UTC, BeokBeok commented on domain/src/main/java/edu/nextstep/camp/calculator/domain/Calculator.kt
> +class Calculator {
제가 설명이 부족했네요.
클래스에는 최소 하나 이상의 생성자를 가지도록 작성하는 것이 좋습니다.
하지만, 생성자가 없다면 object를 활용하는 것을 권장한다는 의미였습니다.

2022-01-23 05:51 UTC, BeokBeok approved these changes
피드백 반영해주시느라 고생하셨습니다 👍 
추가로 고민해볼만한 의견들을 코맨트로 작성하였으니, 충분히 고민해보시고 도전해보세요 💪 
다음 미션과 함께, 작성된 코맨트들을 반영해주세요 🙏

2022-01-23 05:51 UTC, BeokBeok commented on domain/src/main/java/edu/nextstep/camp/calculator/domain/Calculator.kt
> +    }
Calculator의 역할이 아닌 Operator의 역할로 보여요.
이 로직을 Operator로 옮기면 어떨까요?

2022-01-23 05:51 UTC, BeokBeok commented on domain/src/main/java/edu/nextstep/camp/calculator/domain/Calculator.kt
> +    }
char라는 변수는 어떤 것을 의미할까요?
변수명을 보다 의미있게 작성해보면 좋을 것 같아요.

2022-01-23 05:51 UTC, BeokBeok commented on domain/src/main/java/edu/nextstep/camp/calculator/domain/Operator.kt
> +        }
제가 링크를 잘못 드렸었네요 😭 
람다 혹은 인터페이스를 활용하면 좋을 것 같아요.

ref. https://kotlinlang.org/docs/enum-classes.html#anonymous-classes
ref. https://kotlinlang.org/docs/enum-classes.html#implementing-interfaces-in-enum-classes

2022-01-23 05:51 UTC, merged

2022-01-24 13:58 UTC, chohohee commented on domain/src/main/java/edu/nextstep/camp/calculator/domain/Calculator.kt
> +class Calculator {
이해가 되었습니다!